# Generated by Django 3.1.6 on 2021-02-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.URLField(default='https://place-hold.it/100x60', max_length=150),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.URLField(default='https://place-hold.it/100x60', max_length=150),
        ),
    ]
