# Generated by Django 3.1.6 on 2021-02-17 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('vacancies', '0002_auto_20210214_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=48)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_username', models.CharField(max_length=48)),
                ('written_phone', models.CharField(max_length=12)),
                ('written_cover_letter', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(
                    default=None,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='applications',
                    to='vacancies.user')),
                ('vacancy', models.ForeignKey(
                    default=None,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='applications',
                    to='vacancies.vacancy')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(
                default=None, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='companies',
                to='vacancies.user'),
        ),
    ]
