# Generated by Django 3.1.6 on 2021-02-21 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0010_auto_20210221_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='companies',
                to='auth.user'),
        ),
    ]
